services:
    - type: web
      name: britva-app
      env: docker
      dockerfilePath: Dockerfile.render
      plan: starter
      buildCommand: |
          php artisan optimize
          npm install && npm run build
      startCommand: 'php artisan serve --host 0.0.0.0 --port $PORT'
      healthCheckPath: /
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_URL
            fromService:
                name: britva-app
                type: web
                property: host
          - key: DB_CONNECTION
            value: pgsql
          - key: DB_HOST
            fromService:
                name: britva-db
                type: pserv
                property: host
          - key: DB_PORT
            value: 5432
          - key: DB_DATABASE
            fromService:
                name: britva-db
                type: pserv
                property: database
          - key: DB_USERNAME
            fromService:
                name: britva-db
                type: pserv
                property: username
          - key: DB_PASSWORD
            fromService:
                name: britva-db
                type: pserv
                property: password
          - key: SESSION_DRIVER
            value: database
          - key: CACHE_DRIVER
            value: database
          - key: QUEUE_CONNECTION
            value: database
          - key: APP_KEY
            generateValue: true
          - key: LOG_CHANNEL
            value: stderr

    - type: pserv
      name: britva-db
      env: docker
      plan: starter
      repo: https://github.com/render-examples/postgresql.git
      envVars:
          - key: POSTGRES_USER
            value: britva
          - key: POSTGRES_PASSWORD
            generateValue: true
          - key: POSTGRES_DB
            value: britva
      disk:
          name: data
          mountPath: /var/lib/postgresql/data
          sizeGB: 10
